In [1]:
#import required libraries
import pandas as pd
import numpy as np
# Show all columns in output
pd.set_option('display.max_columns', None)
print("Libraries loaded successfully")

Libraries loaded successfully

In [12]:
# Load the dataset

file_path = r"C:\Users\vidiy\OneDrive\Desktop\1st\Combined_dataset.csv"

try:
    df = pd.read_csv(file_path)

    print("Dataset loaded successfully!")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

except FileNotFoundError:
    print("File not found. Please check the file path.")

except Exception as e:
    print("Error:", e)

Dataset loaded successfully!
Rows: 1000
Columns: 24

In [13]:
# Display first 5 rows of the dataset

print("First 5 Rows:")
display(df.head())

First 5 Rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue solid backpackNon-Pa...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy Blue backpackNon-Padded h...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Pink solid backpacks Non-padd...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Navy and grey printed backpack...","[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Blue solid bath robe, has a sh...","[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [14]:
# Check dataset size and column names

print("Dataset Shape:")
print(df.shape)
print("\nColumn Names:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

Dataset Shape:
(1000, 24)

Column Names:
1. product_id
2. title
3. product_description
4. rating
5. ratings_count
6. initial_price
7. discount
8. final_price
9. currency
10. images
11. delivery_options
12. product_details
13. breadcrumbs
14. product_specifications
15. amount_of_stars
16. what_customers_said
17. seller_name
18. sizes
19. videos
20. seller_information
21. variations
22. best_offer
23. more_offers
24. category

In [15]:
# Display dataset information
print("Dataset Information:\n")
df.info()
# Display count of each data type
print("\nData Type Summary:")
print(df.dtypes.value_counts())
# Separate numeric and non-numeric columns
numeric_cols = df.select_dtypes(
    include=['int64', 'float64']
).columns

text_cols = df.select_dtypes(
    include=['object']
).columns
print("\nNumber of Numeric Columns :", len(numeric_cols))
print("Number of Text Columns    :", len(text_cols))

print("\nNumeric Columns:")
for col in numeric_cols:
    print("-", col)
print("\nText Columns:")
for col in text_cols:
    print("-", col)

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

Data Type Summary:
object     19
int64       3
float64     2
Name: count, dtype: int64

Number of Numeric Columns : 5
Number of Text Columns    : 19

Numeric Columns:
- product_id
- rating
- ratings_count
- initial_price
- discount

Text Columns:
- title
- product_description
- final_price
- currency
- images
- delivery_options
- product_details
- breadcrumbs
- product_specifications
- amount_of_stars
- what_customers_said
- seller_name
- sizes
- videos
- seller_information
- variations
- best_offer
- more_offers
- category

In [16]:
# Statistical summary of numeric columns

print("Statistical Summary:\n")
summary = df.describe().round(2)
display(summary)
# Additional insights
print("\nTotal Numeric Columns :", len(summary.columns))
print("Total Records         :", len(df))

Statistical Summary:

        product_id   rating  ratings_count  initial_price  discount
count      1000.00  1000.00        1000.00        1000.00    879.00
mean   17134372.58     3.62          76.69        2723.24     53.50
std     3813765.76     1.37         241.11        2408.70     18.03
min      586846.00     0.00           0.00         249.00      1.00
25%    15115009.50     3.70           7.00        1399.00     44.00
50%    18208901.00     4.10          17.00        1999.00     56.00
75%    19027372.00     4.30          58.00        3299.00     66.00
max    22747068.00     5.00        4441.00       22199.00     88.00

Total Numeric Columns : 5
Total Records         : 1000

In [17]:
df.describe().round(2)

        product_id   rating  ratings_count  initial_price  discount
count      1000.00  1000.00        1000.00        1000.00    879.00
mean   17134372.58     3.62          76.69        2723.24     53.50
std     3813765.76     1.37         241.11        2408.70     18.03
min      586846.00     0.00           0.00         249.00      1.00
25%    15115009.50     3.70           7.00        1399.00     44.00
50%    18208901.00     4.10          17.00        1999.00     56.00
75%    19027372.00     4.30          58.00        3299.00     66.00
max    22747068.00     5.00        4441.00       22199.00     88.00

In [20]:
# Check for missing values in the dataset
null_counts = df.isnull().sum()
# Calculate percentage of missing values
null_percentage = (
    null_counts / len(df) * 100
).round(2)
# Create a summary table
null_summary = pd.DataFrame({
    'Missing Values': null_counts,
    'Percentage (%)': null_percentage
})
# Show only columns with missing values
null_summary = null_summary[
    null_summary['Missing Values'] > 0
]

print("Missing Value Analysis:\n")

display(null_summary)

Missing Value Analysis:

                    Missing Values  Percentage (%)
discount                       121            12.1
videos                         781            78.1
seller_information             301            30.1
variations                     562            56.2

In [21]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [44]:
# Handle missing values

# Fill missing seller names
df['seller_name'] = df['seller_name'].fillna('Unknown')

# Fill missing ratings with median
df['rating'] = df['rating'].fillna(
    df['rating'].median()
)

# Fill missing ratings count with median
df['ratings_count'] = df['ratings_count'].fillna(
    df['ratings_count'].median()
)

# Remove rows where title is missing
df = df.dropna(subset=['title'])

print("Missing values handled successfully!")

print(df.isnull().sum())

Missing values handled successfully!
product_id       0
title            0
seller_name      0
initial_price    0
final_price      0
rating           0
ratings_count    0
dtype: int64

In [45]:
# Remove duplicate rows from the dataset

before = len(df)
df = df.drop_duplicates()
after = len(df)
print("Duplicate rows removed successfully!")

print("Rows before cleaning :", before)
print("Rows after cleaning  :", after)
print("Duplicates removed   :", before - after)

Duplicate rows removed successfully!
Rows before cleaning : 1000
Rows after cleaning  : 1000
Duplicates removed   : 0

In [46]:
# Clean price columns

def clean_price(series):

    return (
        series.astype(str)
        .str.replace('₹', '', regex=False)
        .str.replace(',', '', regex=False)
        .str.strip()
        .astype(float)
    )
# Convert price columns to numeric format
df['initial_price'] = clean_price(df['initial_price'])
df['final_price'] = clean_price(df['final_price'])
print("Price columns cleaned successfully!")
print("\nFirst 3 rows:")
print(df[['initial_price', 'final_price']].head(3))

Price columns cleaned successfully!

First 3 rows:
   initial_price  final_price
0         3995.0       3995.0
1         2899.0       2899.0
2         2999.0       2999.0

In [60]:
# Select important columns for analysis

useful_cols = [
    'product_id',
    'title',
    'initial_price',
    'final_price',
    'rating',
    'ratings_count'
]
df = df[useful_cols].copy()
# Filter products with rating 4 or above
df_filtered = df[df['rating'] >= 4]
print("Filtered Products :", len(df_filtered))
print("Remaining Products:", len(df) - len(df_filtered))
# Display first few filtered records
df_filtered.head(10)

Filtered Products : 615
Remaining Products: 385

,product_id,title,initial_price,final_price,rating,ratings_count
1,9136281,Tommy Hilfiger,2899.0,2899.0,4.5,67
2,17633752,Lavie,2999.0,2999.0,4.4,226
3,1376949,F Gear,1675.0,1675.0,4.4,1052
4,13939916,MYTRIDENT,2899.0,2899.0,4.7,12
5,17198778,H&M,1399.0,1399.0,4.5,42
6,19851824,AVI Living,1399.0,1399.0,4.0,5
7,18602872,My Room,2999.0,2999.0,4.7,10
8,18602850,My Room,2999.0,2999.0,4.5,22
10,8430275,MYTRIDENT,2199.0,2199.0,4.4,26
15,19788630,Home Ecstasy,1199.0,1199.0,4.5,6

In [61]:
# Remove duplicate records
before = len(df)
# Remove duplicate rows
df = df.drop_duplicates()
after = len(df)
print("Duplicate rows removed successfully!")
print("Rows before :", before)
print("Rows after  :", after)
print("Duplicates removed :", before - after)

Duplicate rows removed successfully!
Rows before : 1000
Rows after  : 1000
Duplicates removed : 0

In [63]:
# Create derived columns

# Generate random quantity values between 1 and 5
np.random.seed(42)

df_filtered['quantity'] = np.random.randint(
    1,
    6,
    size=len(df_filtered)
)
# Calculate total amount
df_filtered['total_amount'] = (
    df_filtered['final_price'] *
    df_filtered['quantity']
)
print("Derived columns added successfully!")
# Display first 5 rows
# Display first 5 rows with 10 columns

df_filtered[
    [
        'product_id',
        'title',
        'initial_price',
        'final_price',
        'rating',
        'ratings_count',
        'quantity',
        'total_amount'
    ]
].head()

Derived columns added successfully!

,product_id,title,initial_price,final_price,rating,ratings_count,quantity,total_amount
1,9136281,Tommy Hilfiger,2899.0,2899.0,4.5,67,4,11596.0
2,17633752,Lavie,2999.0,2999.0,4.4,226,5,14995.0
3,1376949,F Gear,1675.0,1675.0,4.4,1052,3,5025.0
4,13939916,MYTRIDENT,2899.0,2899.0,4.7,12,5,14495.0
5,17198778,H&M,1399.0,1399.0,4.5,42,5,6995.0

In [66]:
# Generate summary statistics

summary = {
    "Total Filtered Products"     : len(df_filtered),
    "Average Final Price (₹)"     : round(df_filtered['final_price'].mean(), 2),
    "Average Rating"              : round(df_filtered['rating'].mean(), 2),
    "Total Revenue (₹)"           : round(df_filtered['total_amount'].sum(), 2),
    "Average Revenue per Product" : round(df_filtered['total_amount'].mean(), 2),
}

print("Summary Statistics\n" + "-" * 40)

for key, value in summary.items():
    print(f"{key:30}: {value}")

Summary Statistics
----------------------------------------
Total Filtered Products       : 615
Average Final Price (₹)       : 1772.37
Average Rating                : 4.33
Total Revenue (₹)             : 3186964.0
Average Revenue per Product   : 5182.06

In [67]:
# Export cleaned dataset

OUTPUT_PATH = r"C:\Users\vidiy\OneDrive\Desktop\1st\cleaned_dataset.csv"

try:

    df_filtered.to_csv(
        OUTPUT_PATH,
        index=False
    )

    print("Cleaned dataset exported successfully!")

    print(f"\nSaved file location : {OUTPUT_PATH}")

    print(
        f"Final Dataset Shape : "
        f"{df_filtered.shape[0]} rows × "
        f"{df_filtered.shape[1]} columns"
    )

except Exception as e:

    print(f"Error saving file: {e}")

Cleaned dataset exported successfully!

Saved file location : C:\Users\vidiy\OneDrive\Desktop\1st\cleaned_dataset.csv
Final Dataset Shape : 615 rows × 8 columns

In [68]:
print("Raw Dataset Shape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

Raw Dataset Shape:
(1000, 6)

Columns:
['product_id', 'title', 'initial_price', 'final_price', 'rating', 'ratings_count']

In [78]:
print("Cleaned Dataset Shape:")
print(df_filtered.shape)
df_filtered.head()

Cleaned Dataset Shape:
(615, 8)

,product_id,title,initial_price,final_price,rating,ratings_count,quantity,total_amount
1,9136281,Tommy Hilfiger,2899.0,2899.0,4.5,67,4,11596.0
2,17633752,Lavie,2999.0,2999.0,4.4,226,5,14995.0
3,1376949,F Gear,1675.0,1675.0,4.4,1052,3,5025.0
4,13939916,MYTRIDENT,2899.0,2899.0,4.7,12,5,14495.0
5,17198778,H&M,1399.0,1399.0,4.5,42,5,6995.0